music_app_exam_prep/music_app_exam_prep/album/urls.py
from django.urls import path, include
from music_app_exam_prep.album import views

urlpatterns = [
    path('add/', views.AlbumCreateView.as_view(), name='add_album'),
    path('<int:id>/', include([
        path('details/', views.AlbumDetailsView.as_view(), name='album_details'),
        path('edit/', views.AlbumEditView.as_view(), name='album_edit'),
        path('delete/', views.AlbumDeleteView.as_view(), name='album_delete'),
    ])),
]

music_app_exam_prep/music_app_exam_prep/common/urls.py
from django.urls import path
from music_app_exam_prep.common import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
]

music_app_exam_prep/music_app_exam_prep/profiles/urls.py
from django.urls import path
from music_app_exam_prep.profiles import views

urlpatterns = [
    path('details/', views.ProfileDetailsView.as_view(), name='profile_details'),
    path('delete/', views.ProfileDeleteView.as_view(), name='profile_delete'),
]

music_app_exam_prep/music_app_exam_prep/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music_app_exam_prep.common.urls')),
    path('album/', include('music_app_exam_prep.album.urls')),
    path('profile/', include('music_app_exam_prep.profiles.urls')),
]

music_app_exam_prep/music_app_exam_prep/album/models.py
from django.core.validators import MinValueValidator
from django.db import models

from music_app_exam_prep.album.choices import GenreChoices
from music_app_exam_prep.profiles.models import Profile


# Create your models here.

class Album(models.Model):
    album_name = models.CharField(
        max_length=30,
        unique=True,
    )

    artist = models.CharField(
        max_length=30,
    )

    genre = models.CharField(
        max_length=30,
        choices=GenreChoices.choices,
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    image_url = models.URLField()

    price = models.FloatField(
        validators=[MinValueValidator(0.1)],
    )

    owner = models.ForeignKey(
        to=Profile,
        on_delete=models.CASCADE,
        related_name='albums',
    )

music_app_exam_prep/music_app_exam_prep/common/models.py
from django.db import models

# Create your models here.

music_app_exam_prep/music_app_exam_prep/profiles/models.py
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models


# Create your models here.

class Profile(models.Model):
    username = models.CharField(
        max_length=15,
        validators=[
            MinLengthValidator(2),
            RegexValidator(
                regex=r"^[A-Za-z0-9_]*$",
                message="Ensure this value contains only letters, numbers, and underscore."
            )
        ]
    )

    email = models.EmailField()

    age = models.PositiveIntegerField(
        blank=True,
        null=True,
    )

music_app_exam_prep/music_app_exam_prep/album/forms.py
from django import forms
from music_app_exam_prep.album.models import Album
from music_app_exam_prep.mixins import PlaceholderMixin, ReadOnlyMixin


class AlbumBaseForm(forms.ModelForm):
    class Meta:
        model = Album
        exclude = ('owner',)


class CreateAlbumForm(PlaceholderMixin, AlbumBaseForm):
    pass


class DeleteAlbumForm(ReadOnlyMixin, AlbumBaseForm):
    read_only_fields = ['album_name', 'artist', 'genre', 'price', 'description']

music_app_exam_prep/music_app_exam_prep/profiles/forms.py
from django import forms

from music_app_exam_prep.profiles.models import Profile


class ProfileCreationForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username'})
    )

    email = forms.EmailField(widget=forms.TextInput(attrs={
        'placeholder': 'Email'
    }))

    age = forms.IntegerField(widget=forms.NumberInput(attrs={
        'placeholder': 'Age'
    }))


class ProfileDeletionForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

music_app_exam_prep/music_app_exam_prep/album/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from music_app_exam_prep.album.forms import CreateAlbumForm, DeleteAlbumForm
from music_app_exam_prep.album.models import Album
from music_app_exam_prep.utils import get_user_obj


# Create your views here.

class AlbumCreateView(CreateView):
    model = Album
    form_class = CreateAlbumForm
    template_name = 'album/album-add.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.owner = get_user_obj()
        return super().form_valid(form)


class AlbumDetailsView(DetailView):
    model = Album
    template_name = 'album/album-details.html'
    pk_url_kwarg = 'id'


class AlbumEditView(UpdateView):
    model = Album
    form_class = CreateAlbumForm
    template_name = 'album/album-edit.html'
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('home')


# def album_delete(request):
#     return render(request, 'album/album-delete.html')


class AlbumDeleteView(DeleteView):
    model = Album
    form_class = DeleteAlbumForm
    template_name = 'album/album-delete.html'
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('home')

    def get_initial(self):
        return self.object.__dict__

    def form_invalid(self, form):
        return self.form_valid(form)

music_app_exam_prep/music_app_exam_prep/common/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import BaseFormView

from music_app_exam_prep.album.models import Album
from music_app_exam_prep.profiles.forms import ProfileCreationForm
from music_app_exam_prep.utils import get_user_obj


# Create your views here.

class HomePage(ListView, BaseFormView):
    model = Album
    form_class = ProfileCreationForm
    success_url = reverse_lazy('home')

    def get_template_names(self):
        profile = get_user_obj()
        if not profile:
            return ['common/home-no-profile.html']

        return ['common/home-with-profile.html']

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

music_app_exam_prep/music_app_exam_prep/profiles/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, DeleteView
from music_app_exam_prep.utils import get_user_obj


# Create your views here.

class ProfileDetailsView(DetailView):
    template_name = 'profile/profile-details.html'

    def get_object(self, queryset=None):
        return get_user_obj()


class ProfileDeleteView(DeleteView):
    template_name = 'profile/profile-delete.html'
    success_url = reverse_lazy('home')

    def get_object(self, queryset=None):
        return get_user_obj()

music_app_exam_prep/templates/common/base.html
{% load get_user %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>My Music App</title>
    <!-- Static Load -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<div id="box">
    <!-- Navigation Bar -->
    <header>
        <nav>
            <img src="{% static 'images/headphones.png' %}" alt="headphones"/>
            <a href="{% url 'home' %}">Home</a>
            <ul></ul>
            {% get_user as profile %}
            {% if profile %}
                <ul>
                    <!--Only for user with created profile-->
                    <li><a href="{% url 'add_album' %}">Create Album</a></li>
                    <li><a href="{% url 'profile_details' %}">Profile</a></li>
                </ul>
            {% endif %}
        </nav>
    </header>
    <!-- End Navigation Bar -->
    {% block content %}
    {% endblock %}
    <!-- Footer -->
    <footer>
        <div>&copy;SoftUni Team 2024. All rights reserved.</div>
    </footer>
    <!-- End Footer -->
</div>
</body>
</html>

music_app_exam_prep/templates/common/home-no-profile.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
    
    <div class="container-inline">
        <section id="welcomePage">
            <div id="welcome-message">
                <h1>Welcome to</h1>
                <h1>My Music App!</h1>
            </div>
            <div class="music-img">
                <img src="{% static 'images/musicIcons.webp' %}" alt="music-icon"/>
            </div>
        </section>
        <section id="registerPage">
            <form method="POST">
                <fieldset>
                    <legend>Profile</legend>
                    {{ form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="register">Enter</button>
                </fieldset>
            </form>
        </section>
    </div>

{% endblock %}

music_app_exam_prep/templates/common/home-with-profile.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}

    <!-- Main Content -->
    <!-- Catalog with Albums-->
    <section id="catalogPage">
        {% if not album_list %}
            <!--  If No albums in catalog -->
            <p>No Albums in Catalog!</p>
        {% else %}
            <!-- If albums in catalog -->
            <h1>All Albums</h1>
        {% endif %}
        <!-- First Card-Box in catalog -->
        {% for album in album_list %}
            <div class="card-box">
                <img src="{{ album.image_url }}" alt="Cover Image"/>
                <div>
                    <div class="text-center">
                        <p class="name">Name: {{ album.album_name }}</p>
                        <p class="artist">Artist: {{ album.artist }}</p>
                        <p class="genre">Genre: {{ album.genre }}</p>
                        <p class="price">Price: ${{ album.price|floatformat:2 }}</p>
                    </div>
                    <div class="btn-group">
                        <a href="{% url 'album_details' album.id %}">Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        <!-- End First Card-Box in catalog -->
    </section>

{% endblock %}

music_app_exam_prep/templates/profile/profile-delete.html
{% extends 'common/base.html' %}

{% block content %}
    
    <section id="detailsPage">
        <div class="wrapper">
            <div class="profileText">
                <!-- Delete Profile Form -->
                <h1>Are you sure you want to delete your profile?</h1>
                <form method="POST">
                    {% csrf_token %}
                    <!-- Confirm Button -->
                    <button class="delete-profile" type="submit">Delete</button>
                </form>
                <!-- End Delete Profile Form -->
            </div>
        </div>
    </section>
    
{% endblock %}

music_app_exam_prep/templates/profile/profile-details.html
{% extends 'common/base.html' %}

{% block content %}
    
    <section id="detailsPage">
        <div class="wrapper">
            <div class="profilePage">
                <img
                        src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
                        alt="Profile Image"
                />
            </div>

            <div class="profileText">
                <!-- Profile Info -->
                <h1>Username: {{ profile.username }}</h1>
                <h1>Email: {{ profile.email }}</h1>
                <h1>Age: {{ profile.age }}</h1>
                <h1>Albums: {{ profile.albums.count }}</h1>
            </div>

            <div class="actionBtn">
                <!-- Button for Deleting the Profile -->
                <a href="{% url 'profile_delete' %}" class="remove">Delete</a>
            </div>
        </div>
    </section>
    
{% endblock %}